language: python

services: 
  - mysql

env:
  global:
    - BUILD_ON_TRAVIS=true
    - PIP_USE_MIRRORS=true
    - DJANGO=2.0.12
    - DB=mysql

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - "flake8 --exclude=manage.py,./apps/main/migrations/,./core/settings.py"
  - "python3 manage.py test"
