language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

matrix:
  include:
    - python: "3.6"
      script:
        - "flake8 --exclude=manage.py /apps/main/migrations/"
        - "python3 manage.py test"
