version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - '/srv/mysql:/var/lib/mysql'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_DB_NAME}
      MYSQL_USER: ${TEST_DB_USER}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5666
    restart: always
    ports:
      - "5666:5666"
    expose:
      - '5666'
    depends_on:
      - db
