# Generated by Django 2.0 on 2018-05-23 08:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('short_description', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=5)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('free_shipping', models.BooleanField()),
                ('available', models.BooleanField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('file', models.FileField(upload_to='uploaded_files')),
                ('status', models.CharField(blank=True, choices=[('N', 'None'), ('P', 'Pending'), ('B', 'Begin'), ('S', 'Success'), ('E', 'Error'), ('A', 'Almost')], default='N', max_length=20)),
                ('log', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Uploaded files',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Retailer'),
        ),
    ]
