# Generated by Django 2.0.12 on 2019-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('name_for_crauler', models.CharField(max_length=40, null=True, verbose_name='Main slug')),
                ('url', models.CharField(max_length=150, verbose_name='Url')),
            ],
        ),
    ]
