# Generated by Django 2.0.12 on 2019-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('scraper', '0001_initial'), ('scraper', '0002_auto_20190813_1306'), ('scraper', '0003_site_name_for_crauler'), ('scraper', '0004_auto_20190827_0734')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('main_url', models.CharField(max_length=50, verbose_name='Main url')),
                ('slug', models.CharField(max_length=100, verbose_name='Pseudo slug')),
                ('name_for_crauler', models.SlugField(max_length=40, null=True, verbose_name='Main slug')),
            ],
        ),
    ]
