# Generated by Django 2.0.12 on 2019-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('scraper', '0002_auto_20190828_0950'), ('scraper', '0003_auto_20190828_0954'), ('scraper', '0004_auto_20190828_0956')]

    dependencies = [
        ('scraper', '0001_squashed_0004_auto_20190827_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='main_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=150, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name_for_crauler',
            field=models.CharField(max_length=40, null=True, verbose_name='Main slug'),
        ),
    ]
