# Generated by Django 2.0.12 on 2019-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Pseudo slug'),
        ),
    ]
