# Generated by Django 2.0.12 on 2019-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_site_name_for_crauler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name_for_crauler',
            field=models.SlugField(max_length=40, null=True, verbose_name='Main slug'),
        ),
    ]
